name: DesignCircuit
favicon: null
layout_spectrum: 0.49759
typography_spectrum: 0.4988
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7941d'
    - '#ffffff'
    - '#272262'
    - '#bd7430'
    - '#583c50'
  brandStrength: 0
  lightness: 0.5465397061780095
  saturation: 0.1875
  rhythmicContrast: 0.5496229489799589
purpose: []
